#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2010-2017 GEM Foundation
#
# The OQ-CATK (Lite) is free software: you can redistribute
# it and/or modify it under the terms of the GNU Affero General Public
# License as published by the Free Software Foundation, either version
# 3 of the License, or (at your option) any later version.
#
# OQ-CATK (Lite) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# with this download. If not, see <http://www.gnu.org/licenses/>
#
# Author: Poggi Valerio

#-----------------------------------------------------------------------------------------

def Print(Key):
  if Key in Code.keys():
    print 'CODE: {0}'.format(Key)
    print 'AGENCY: {0}'.format(Code[Key][0])
    print 'COUNTRY: {0}'.format(Code[Key][1])
  else:
    print 'Warning: Code not found'

Code = {'AAA' : ['Alma-ata','Kazakhstan'],
        'AAB' : ['Alma-ata 2','Kazakhstan'],
        'AAC' : ['Unknown Historical Agency',''],
        'AAE' : ['University of Addis Ababa','Ethiopia'],
        'AAM' : ['University of Michigan','U.S.A.'],
        'ABA' : ['Alger-bouzareah','Algeria'],
        'ACI' : ['Universita di Calabria','Italy'],
        'ADE' : ['Primary Industries and Resources SA','Australia'],
        'ADH' : ['Observatorio Afonso Chaves','Portugal'],
        'AEIC' : ['Alaska Earthquake Information Center','U.S.A.'],
        'AFAR' : ['The Afar Depression: Interpretation of the 1960-2000 Earthquakes','Israel'],
        'AFI' : ['Apia Observatory','Western Samoa'],
        'AGS' : ['Alaska Seismic Project','U.S.A.'],
        'ALG' : ['Algiers University','Algeria'],
        'ALI' : ['Observatorio Sismologico Vicente Inglada','Spain'],
        'ALM' : ['Instituto Geografico y Catastral de Almeria','Spain'],
        'ANCORP' : ['Andean Continental Research Project','Germany'],
        'ANF' : ['USArray Array Network Facility','U.S.A.'],
        'ANT' : ['Antofagasta','Chile'],
        'ANUBIS' : ['Antarctic Network of Broadband Seismometers','U.S.A.'],
        'APA' : ['Apatity','Russia'],
        'API' : ['Apia Observatory','Western Samoa'],
        'APT' : ['University of Connecticut','U.S.A.'],
        'AQU' : ['Aquila','Italy'],
        'ARA0' : ['Arcess Array','Norway'],
        'ARE' : ['Instituto Geofisico del Peru','Peru'],
        'ARO' : ['Observatoire Géophysique d\'Arta','Djibouti'],
        'ASIES' : ['Institute of Earth Sciences, Academia Sinica','Chinese Taipei'],
        'ASL' : ['Albuquerque Seismological Laboratory','U.S.A.'],
        'ASM' : ['University of Asmara','Eritrea'],
        'ASRS' : ['Altai-Sayan Seismological Centre','Russia'],
        'ATA' : ['The Earthquake Research Center Ataturk University','Turkey'],
        'ATH' : ['National Observatory of Athens','Greece'],
        'AUST' : ['Geoscience Australia','Australia'],
        'AVE' : ['Averroes','Morocco'],
        'AWI' : ['Alfred Wegener Institute for Polar and Marine Research','Germany'],
        'AZER' : ['Republic Center of Seismic Survey','Azerbaijan'],
        'AZO' : ['Centro de Informação e Vigilância Sismovulcânica dos Azores','Portugal'],
        'BAA' : ['Servicio Meteorologico Nacional','Argentina'],
        'BAK' : ['Unknown Historical Agency',''],
        'BANJO' : ['Broadband ANdean JOint Experiment','U.S.A.'],
        'BASV' : ['British Antarctic Survey','United Kingdom'],
        'BCIS' : ['Bureau Central International de Sismologie','France'],
        'BDF' : ['Observatório Sismológico da Universidade de Brasília','Brazil'],
        'BELR' : ['Centre of Geophysical Monitoring','Belarus'],
        'BEO' : ['Seismological Survey of Serbia','Serbia'],
        'BER' : ['University of Bergen','Norway'],
        'BERK' : ['Berkheimer H','Germany'],
        'BGLD' : ['Geophysikalisches Observatorium der Ludwig, Maximilians Universität','Germany'],
        'BGR' : ['Bundesanstalt für Geowissenschaften und Rohstoffe','Germany'],
        'BGS' : ['British Geological Survey','United Kingdom'],
        'BHP' : ['Unknown Historical Agency',''],
        'BHUJ' : ['Bhuj Aftershock Study','U.S.A.'],
        'BHUJ2' : ['Study of Aftershocks of the Bhuj Earthquake by Japanese Research Team','Japan'],
        'BIAK' : ['Biak earthquake aftershocks (17-Feb-1996)','U.S.A.'],
        'BJI' : ['China Earthquake Networks Center','China'],
        'BJT' : ['Baijiatuan','China'],
        'BKK' : ['Thai Meteorological Department','Thailand'],
        'BLA' : ['Virginia Tech','U.S.A.'],
        'BNG' : ['Observatoire ORSTOM de Bangui','Central African Republic'],
        'BNS' : ['Erdbebenstation, Geologisches Institut der Universität-Köl','Germany'],
        'BOG' : ['Universidad Javeriana','Colombia'],
        'BOM' : ['Unknown Historical Agency',''],
        'BOU' : ['University of Colorado at Boulder','U.S.A.'],
        'BOZ' : ['Unknown Historical Agency',''],
        'BRA' : ['Geophysical Institute, Slovak Academy of Sciences','Slovakia'],
        'BRG' : ['Seismological Observatory Berggießhübel, TU Bergakademie Freiberg','Germany'],
        'BRK' : ['Berkeley Seismological Laboratory','U.S.A.'],
        'BRS' : ['Brisbane Seismograph Station','Australia'],
        'BSE' : ['Boise State University','U.S.A.'],
        'BUC' : ['National Institute for Earth Physics','Romania'],
        'BUD' : ['Geodetic and Geophysical Research Institute','Hungary'],
        'BUG' : ['Institute of Geology, Mineralogy & Geophysics','Germany'],
        'BUL' : ['Goetz Observatory','Zimbabwe'],
        'BUT' : ['Montana Bureau of Mines and Geology','U.S.A.'],
        'BYKL' : ['Baykal Regional Seismological Centre','Russia'],
        'CADCG' : ['Central America Data Centre','Costa Rica'],
        'CAN' : ['Australian National University','Australia'],
        'CANSK' : ['Canadian and Scandinavian Networks','Sweden'],
        'CAR' : ['Instituto Sismologico de Caracas','Venezuela'],
        'CASC' : ['Central American Seismic Center','Costa Rica'],
        'CDWR' : ['California Department of Water Resources','U.S.A.'],
        'CENT' : ['Centennial Earthquake Catalog','U.S.A.'],
        'CERI' : ['Center for Earthquake Research and Information','U.S.A.'],
        'CGS' : ['Coast and Geodetic Survey of the United States','U.S.A.'],
        'CHM' : ['Unknown Historical Agency',''],
        'CHU' : ['Unknown Historical Agency',''],
        'CIG' : ['Servicio Geologico Nacional de El Salvador','El Salvador'],
        'CINCA' : ['Crustal Investigations Off- and On-shore Nazca - Central Andes','Germany'],
        'CLL' : ['Geophysikalisches Observatorium Collm','Germany'],
        'CMWS' : ['Laboratory of Seismic Monitoring of Caucasus Mineral Water Region','Russia'],
        'CNG' : ['Seismographic Station Changalane','Mozambique'],
        'CNH' : ['Changchun','China'],
        'CNRM' : ['Centre National de Recherche','Morocco'],
        'COI' : ['Unknown Historical Agency',''],
        'COM' : ['Comitan','Mexico'],
        'CON' : ['Unknown Historical Agency',''],
        'COP' : ['Unknown Historical Agency',''],
        'COR' : ['COAS Physical Oceanography','U.S.A.'],
        'COSMOS' : ['Consortium of Organizations for Strong Motion Observations','U.S.A.'],
        'CRA' : ['Unknown Historical Agency',''],
        'CRAAG' : ['Centre de Recherche en Astronomie, Astrophysique et Géophysique','Algeria'],
        'CRT' : ['Cartuja Seismological Station','Spain'],
        'CSC' : ['University of South Carolina','U.S.A.'],
        'CSEM' : ['Centre Sismologique Euro-Méditerranéen (CSEM/EMSC)','France'],
        'DASA' : ['Defense Atomic Support Agency','U.S.A.'],
        'DBN' : ['Koninklijk Nederlands Meteorologisch Instituut','Netherlands'],
        'DDA' : ['Disaster and Emergency Management Presidency','Turkey'],
        'DHMR' : ['Yemen National Seismological Center','Yemen'],
        'DIAS' : ['Dublin Institute for Advanced Studies','Ireland'],
        'DJA' : ['Badan Meteorologi, Klimatologi dan Geofisika','Indonesia'],
        'DMN' : ['Department of Mines and Geology, Ministry of Industry of Nepal','Nepal'],
        'DNK' : ['Geological Survey of Denmark and Greenland','Denmark'],
        'DOE' : ['Department of Energy','U.S.A.'],
        'DRS' : ['Dagestan Branch, Geophysical Survey, Russian Academy of Sciences','Russia'],
        'DSN' : ['Dubai Seismic Network','United Arab Emirates'],
        'DUSS' : ['Damascus University, Syria','Syria'],
        'EAF' : ['East African Network',''],
        'EAGLE' : ['Ethiopia-Afar Geoscientific Lithospheric Experiment',''],
        'EBM' : ['Esen Boulak','Mongolia'],
        'EBR' : ['Observatori de l\'Ebre','Spain'],
        'EBSE' : ['Ethiopian Broadband Seismic Experiment',''],
        'ECX' : ['Red Sismica del Noroeste de Mexico (RESOM)','Mexico'],
        'EFATE' : ['OBS Experiment near Efate, Vanuatu','U.S.A.'],
        'EHB' : ['Engdahl, van der Hilst and Buland','U.S.A.'],
        'EIDC' : ['Experimental (GSETT3) International Data Center','U.S.A.'],
        'EKA' : ['Eskdalemuir Array Station','United Kingdom'],
        'ENT' : ['Geological Survey and Mines Department','Uganda'],
        'EPSI' : ['Reference events computed by the ISC for EPSI project','United Kingdom'],
        'ERDA' : ['Energy Research and Development Administration','U.S.A.'],
        'ERI' : ['Earthquake Research Institute, University of Tokyo','Japan'],
        'ESK' : ['Unknown Historical Agency',''],
        'ESLA' : ['Centro Sismologico de Sonseca','Spain'],
        'EST' : ['Geological Survey of Estonia','Estonia'],
        'EUO' : ['Department of Geological Sciences, University of Oregon','U.S.A.'],
        'FBR' : ['Fabra Observatory','Spain'],
        'FDF' : ['Fort de France','Martinique'],
        'FIA0' : ['Finessa Array','Finland'],
        'FKK' : ['Unknown Historical Agency',''],
        'FOR' : ['Unknown Historical Agency',''],
        'FRU' : ['Unknown Historical Agency',''],
        'FUNV' : ['Fundación Venezolana de Investigaciones Sismológicas','Venezuela'],
        'FUR' : ['Geophysikalisches Observatorium der Universität München','Germany'],
        'GBA' : ['Bhaba Atomic Research Centre','India'],
        'GBZT' : ['Marmara Research Center','Turkey'],
        'GCG' : ['INSIVUMEH','Guatemala'],
        'GCMT' : ['The Global CMT Project','U.S.A.'],
        'GDNRW' : ['Geologischer Dienst Nordrhein-Westfalen','Germany'],
        'GEC2' : ['Geress Array','Germany'],
        'GEN' : ['Dipartimento per lo Studio del Territorio e delle sue Risorse (RSNI)','Italy'],
        'GFZ' : ['Helmholtz Centre Potsdam GFZ German Research Centre For Geosciences','Germany'],
        'GII' : ['The Geophysical Institute of Israel','Israel'],
        'GLD' : ['Golden','U.S.A.'],
        'GM' : ['U.S. Geological Survey','U.S.A.'],
        'GOL' : ['Colorado School of Mines','U.S.A.'],
        'GOM' : ['Observatoire Volcanologique de Goma','Democratic Republic of the Congo'],
        'GRA' : ['Unknown Historical Agency',''],
        'GRA1' : ['Grafenberg Array','Germany'],
        'GRAL' : ['National Council for Scientific Research','Lebanon'],
        'GRO' : ['Unknown Historical Agency',''],
        'GS' : ['U.S. Geological Survey','U.S.A.'],
        'GSAST' : ['Geophysial Survey of the Academy of Sciences of the Republic of Tajikistan','Tajikistan'],
        'GSDM' : ['Geological Survey Department Malawi','Malawi'],
        'GSET2' : ['Group of Scientific Experts Second Technical Test 1991, April 22 - June 2',''],
        'GTFE' : ['German Task Force for Earthquakes','Germany'],
        'GUC' : ['Departamento de Geofísica, Universidad de Chile','Chile'],
        'GUTE' : ['Gutenberg and Richter, Seismicity of the Earth',''],
        'GUV' : ['CVG Electrificacion del Caroni','Venezuela'],
        'HAM' : ['Unknown Historical Agency',''],
        'HAN' : ['Hannover','Germany'],
        'HDC' : ['Observatorio Vulcanológico y Sismológico de Costa Rica','Costa Rica'],
        'HEL' : ['Institute of Seismology, University of Helsinki','Finland'],
        'HFS' : ['Hagfors Observatory','Sweden'],
        'HFS1' : ['Hagfors Observatory','Sweden'],
        'HFS2' : ['Hagfors Observatory','Sweden'],
        'HIMNT' : ['Himalayan Nepal Tibet Experiment','U.S.A.'],
        'HKC' : ['Hong Kong Observatory','Hong Kong'],
        'HLUG' : ['Hessisches Landesamt für Umwelt und Geologie','Germany'],
        'HLW' : ['National Research Institute of Astronomy and Geophysics','Egypt'],
        'HNR' : ['Ministry of Mines, Energy and Rural Electrification','Solomon Islands'],
        'HOKK_DSZ' : ['Hokkaido Double Seismic Zone',''],
        'HON' : ['Pacific Tsunami Warning Center - NOAA','U.S.A.'],
        'HROE' : ['Geophysikalisches Observatorium - Hohe Rhvn-Fladungen','Germany'],
        'HRV' : ['Unknown Historical Agency',''],
        'HRVD' : ['Harvard University','U.S.A.'],
        'HRVD_LR' : ['Department of Geological Sciences, Harvard University','U.S.A.'],
        'HVO' : ['Hawaiian Volcano Observatory','U.S.A.'],
        'HYB' : ['National Geophysical Research Institute','India'],
        'HYD' : ['National Geophysical Research Institute','India'],
        'IAG' : ['Instituto Andaluz de Geofisica','Spain'],
        'IASBS' : ['Institute for Advanced Studies in Basic Sciences','Iran'],
        'IASPEI' : ['IASPEI Working Group on Reference Events','U.S.A.'],
        'IBER' : ['Institute of Earth Sciences Jaume Almera - CSIC','Spain'],
        'ICE' : ['Instituto Costarricense de Electricidad','Costa Rica'],
        'IDC' : ['International Data Centre','Austria'],
        'IDG' : ['Institute of Dynamics of Geosphere, Russian Academy of Sciences','Russia'],
        'IEC' : ['Institute of the Earth Crust','Russia'],
        'IEPN' : ['Institute of Environmental Problems of the North, Russian Academy of Sciences','Russia'],
        'IFREE' : ['Institute For Research on Earth Evolution','Japan'],
        'IGIL' : ['Instituto Geofisico do Infante Dom Luiz','Portugal'],
        'IGQ' : ['Servicio Nacional de Sismología y Vulcanología','Ecuador'],
        'IGS' : ['Institute of Geological Sciences','United Kingdom'],
        'INC' : ['Unknown Historical Agency',''],
        'INDEPTH3' : ['International Deep Profiling of Tibet and the Himalayas','U.S.A.'],
        'INDR' : ['Inst. Nacional de Recursos Hidraulicos','Dominican Republic'],
        'INET' : ['Instituto Nicaragüense de Estudios Territoriales','Nicaragua'],
        'INMG' : ['Instituto Português do Mar e da Atmosfera','Portugal'],
        'INTV' : ['Instituto de Tecnología Venezolana para el Petróleo','Venezuela'],
        'INY' : ['Cornell university (INSTOC)','U.S.A.'],
        'IPEC' : ['The Institute of Physics of the Earth (IPEC)','Czech Republic'],
        'IPER' : ['Institute of Physics of the Earth, Academy of Sciences, Moscow','Russia'],
        'IPGP' : ['Institut de Physique du Globe de Paris','France'],
        'IPRG' : ['Institute for Petroleum Research and Geophysics','Israel'],
        'IRIS' : ['IRIS Data Management Center','U.S.A.'],
        'IRK' : ['Unknown Historical Agency',''],
        'IRSM' : ['Institute of Rock Structure and Mechanics','Czech Republic'],
        'ISC' : ['International Seismological Centre','United Kingdom'],
        'ISC1' : ['International Seismological Centre',''],
        'ISCJB' : ['International Seismological Centre','United Kingdom'],
        'ISK' : ['Kandilli Observatory and Research Institute','Turkey'],
        'ISN' : ['Iraqi Meteorological and Seismology Organisation','Iraq'],
        'ISS' : ['International Seismological Summary','United Kingdom'],
        'IST' : ['Institute of Physics of the Earth, Technical University of Istanbul','Turkey'],
        'JEN' : ['Geodynamisches Observatorium Moxa','Germany'],
        'JER' : ['Seismological Laboratory, Geological Survey of Israel','Israel'],
        'JMA' : ['Japan Meteorological Agency','Japan'],
        'JOH' : ['Bernard Price Institute of Geophysics','South Africa'],
        'JSA' : ['Jesuit Society of America','U.S.A.'],
        'JSN' : ['Jamaica Seismic Network','Jamaica'],
        'JSO' : ['Jordan Seismological Observatory','Jordan'],
        'KAAPVAAL' : ['Kaapvaal Craton Seismic Experiment','U.S.A.'],
        'KAF' : ['Kangasniemi Station','Finland'],
        'KBC' : ['Institut de Recherches Géologiques et Minières','Cameroon'],
        'KBL' : ['Afghanistan Seismological Observatory','Afghanistan'],
        'KEW' : ['Kew Observatory','United Kingdom'],
        'KHC' : ['Geofysikalni Ustav, Ceske Akademie Ved','Czech Republic'],
        'KHO' : ['Khorog','Tajikistan'],
        'KIR' : ['Kiruna','Sweden'],
        'KISR' : ['Kuwait Institute for Scientific Research','Kuwait'],
        'KLM' : ['Malaysian Meteorological Service','Malaysia'],
        'KMA' : ['Korea Meteorological Administration','Republic of Korea'],
        'KNET' : ['Kyrgyz Seismic Network','Kyrgyzstan'],
        'KOB' : ['Unknown Historical Agency',''],
        'KOC' : ['Unknown Historical Agency',''],
        'KOLA' : ['Kola Regional Seismic Centre','Russia'],
        'KRAR' : ['Krasnoyarsk Scientific Research Inst. of Geology and Mineral Resources, Russia','Russia'],
        'KRISP' : ['Kenya Rift International Seismic Project','Germany'],
        'KRL' : ['Geodätisches Institut der Universität Karlsruhe','Germany'],
        'KRNET' : ['Institute of Seismology, Academy of Sciences of Kyrgyz Republic','Kyrgyzstan'],
        'KRSC' : ['Kamchatkan Experimental and Methodical Seismological Department','Russia'],
        'KSA' : ['Observatoire de Ksara','Lebanon'],
        'KUK' : ['Geological Survey Department of Ghana','Ghana'],
        'LAO' : ['Large Aperture Seismic Array','U.S.A.'],
        'LDG' : ['Laboratoire de Détection et de Géophysique/CEA','France'],
        'LDN' : ['University of Western Ontario','Canada'],
        'LDO' : ['Lamont-Doherty Earth Observatory','U.S.A.'],
        'LED' : ['Landeserdbebendienst Baden-Württemberg','Germany'],
        'LEDBW' : ['Landeserdbebendienst Baden-Württemberg','Germany'],
        'LEM' : ['Lembang Station','Indonesia'],
        'LER' : ['Besucherbergwerk Binweide Station','Germany'],
        'LIB' : ['Tripoli','Libya'],
        'LIC' : ['Station Géophysique de Lamto','Ivory Coast'],
        'LIM' : ['Lima','Peru'],
        'LIS' : ['Instituto de Meteorologia','Portugal'],
        'LIT' : ['Geological Survey of Lithuania','Lithuania'],
        'LJU' : ['Environmental Agency of the Republic of Slovenia','Slovenia'],
        'LPA' : ['Universidad Nacional de La Plata','Argentina'],
        'LPB' : ['Unknown Historical Agency',''],
        'LPZ' : ['Observatorio San Calixto','Bolivia'],
        'LRA' : ['Unknown Historical Agency',''],
        'LRSM' : ['Long Range Seismic Measurements Project',''],
        'LSZ' : ['Geological Survey Department of Zambia','Zambia'],
        'LTX' : ['Lajitas Seismic Array','U.S.A.'],
        'LVSN' : ['Latvian Seismic Network','Latvia'],
        'LVV' : ['Department of Seismic Activity of Carpathian area (Lviv)','Ukraine'],
        'LWI' : ['Centre de Geophysique du Zaire','Democratic Republic of the Congo'],
        'MAL' : ['Malaga','Spain'],
        'MAN' : ['Philippine Institute of Volcanology and Seismology','Philippines'],
        'MASS' : ['Marcelo Assumpcao','Brazil'],
        'MAT' : ['The Matsushiro Seismological Observatory','Japan'],
        'MCO' : ['Macao Meteorological and Geophysical Bureau, Macao',' China'],
        'MDD' : ['Instituto Geográfico Nacional','Spain'],
        'MED_RCMT' : ['MedNet Regional Centroid - Moment Tensors','Italy'],
        'MELT' : ['Mantle Electromagnetic and Tomography Experiment','U.S.A.'],
        'MER' : ['Merida','Mexico'],
        'MERI' : ['Maharashta Engineering Research Institute','India'],
        'MES' : ['Messina Seismological Observatory','Italy'],
        'MEX' : ['Instituto de Geofísica de la UNAM','Mexico'],
        'MIRAS' : ['Mining Institute of the Ural Branch of the Russian Academy of Sciences','Russia'],
        'MKY' : ['Unknown Historical Agency',''],
        'MLR' : ['Muntele Rosu Station','Romania'],
        'MNH' : ['Institut für Angewandte Geophysik der Universitat Munchen','Germany'],
        'MOLD' : ['Institute of Geophysics and Geology','Moldova'],
        'MOS' : ['Geophysical Survey of Russian Academy of Sciences','Russia'],
        'MOZ' : ['Direccao Nacional de Geologia','Mozambique'],
        'MRB' : ['Institut Cartogràfic de Catalunya','Spain'],
        'MROB' : ['Geophysikalisches Observatorium - Rosenbuhl','Germany'],
        'MSI' : ['Messina Seismological Observatory','Italy'],
        'MSSP' : ['Micro Seismic Studies Programme','Pakistan'],
        'MSUGS' : ['Michigan State University, Department of Geological Sciences','U.S.A.'],
        'MUM' : ['Manipur University','India'],
        'MUN' : ['Mundaring Observatory','Australia'],
        'MVOV' : ['Montserrat Volcano Observatory','Montserrat'],
        'MZEK' : ['Geophysikalisches Observatorium - Zeckenberg','Germany'],
        'NAG' : ['Unknown Historical Agency',''],
        'NAI' : ['University of Nairobi','Kenya'],
        'NAM' : ['The Geological Survey of Namibia','Namibia'],
        'NAN' : ['Nanking Station','China'],
        'NANGA' : ['Nanga Parbat Seismic Experiment','U.S.A.'],
        'NAO' : ['Stiftelsen NORSAR','Norway'],
        'NCEDC' : ['Northern California Earthquake Data Center','U.S.A.'],
        'NDI' : ['India Meteorological Department','India'],
        'NEIC' : ['National Earthquake Information Center','U.S.A.'],
        'NEIS' : ['National Earthquake Information Service','U.S.A.'],
        'NERS' : ['North Eastern Regional Seismological Centre','Russia'],
        'NEU' : ['Neuchatel Station','Switzerland'],
        'NIC' : ['Cyprus Geological Survey Department','Cyprus'],
        'NIED' : ['National Research Institute for Earth Science and Disaster Prevention','Japan'],
        'NNC' : ['National Nuclear Center','Kazakhstan'],
        'NORI' : ['Geophysikalisches Observatorium - Nordlinger Ries','Germany'],
        'NORS' : ['North Ossetia (Alania) Branch, Geophysical Survey, Russian Academy of Sciences','Russia'],
        'NOU' : ['IRD Centre de Nouméa','New Caledonia'],
        'NPO' : ['North Pole Environmental Observatory','U.S.A.'],
        'NRA0' : ['Noress Array','Norway'],
        'NSSC' : ['National Syrian Seismological Center','Syria'],
        'NSSP' : ['National Survey of Seismic Protection','Armenia'],
        'NUR' : ['Nurmijarvi Station','Finland'],
        'OAX' : ['Oaxaca','Mexico'],
        'OBER' : ['Geophysikalisches Observatorium - Oberstdorf','Germany'],
        'OBM' : ['Research Centre of Astronomy and Geophysics','Mongolia'],
        'OGA' : ['Geophysikalisches Observatorium - Obergurgl/A','Germany'],
        'OGSO' : ['Ohio Geological Survey','U.S.A.'],
        'OMAN' : ['Sultan Qaboos University','Oman'],
        'ORF' : ['Orfeus Data Center','Netherlands'],
        'OSA' : ['Osa Peninsula Project, Costa Rica','U.S.A.'],
        'OSS' : ['Ova Spin','Switzerland'],
        'OSUB' : ['Osservatorio Sismologico Universita di Bari','Italy'],
        'OTT' : ['Canadian Hazards Information Service, Natural Resources Canada','Canada'],
        'OXD' : ['Unknown Historical Agency',''],
        'PAL' : ['Palisades','U.S.A.'],
        'PANAMA97' : ['Panama Canal Seismicity Study','U.S.A.'],
        'PAS' : ['California Institute of Technology','U.S.A.'],
        'PAV' : ['Pavia','Italy'],
        'PDA' : ['Universidade dos Açores','Portugal'],
        'PDE' : ['Preliminary Determination of Epicentres','U.S.A.'],
        'PDG' : ['Seismological Institute of Montenegro','Montenegro'],
        'PEK' : ['Peking','China'],
        'PFO' : ['Pinyon Flat Observatory','U.S.A.'],
        'PGC' : ['Pacific Geoscience Centre','Canada'],
        'PIN' : ['Pinedale Seismic Array','U.S.A.'],
        'PISCO' : ['Proyecto de Investigacion Sismologica de la Cordillera Occidental','Germany'],
        'PIST' : ['P. Stahl','France'],
        'PIT' : ['Unknown Historical Agency',''],
        'PLV' : ['National Center for Scientific Research','Vietnam'],
        'PMEL' : ['Pacific seismicity from hydrophones','U.S.A.'],
        'PMG' : ['Port Moresby Geophysical Observatory','Papua New Guinea'],
        'PMR' : ['Alaska Tsunami Warning Center','U.S.A.'],
        'PNG' : ['Unknown Historical Agency',''],
        'PNNL' : ['Pacific Northwest National Laboratory','U.S.A.'],
        'PNSN' : ['Pacific Northwest Seismic Network','U.S.A.'],
        'POO' : ['Poona Observatory','India'],
        'PPT' : ['Laboratoire de Géophysique/CEA','French Polynesia'],
        'PRA' : ['Academy of Sciences of the Czech Republic','Czech Republic'],
        'PRE' : ['Council for Geoscience','South Africa'],
        'PRT' : ['Observatorio San Domenico','Italy'],
        'PRU' : ['Geophysical Institute, Academy of Sciences of the Czech Republic','Czech Republic'],
        'PTO' : ['Instituto Geofísico da Universidade do Porto','Portugal'],
        'PTWC' : ['Pacific Tsunami Warning Center','U.S.A.'],
        'PUL' : ['Unknown Historical Agency',''],
        'PUNA' : ['Puna Plateau, Argentina and Northern Chile Experiment','Germany'],
        'PUS' : ['Unknown Historical Agency',''],
        'PYA' : ['Unknown Historical Agency',''],
        'QCP' : ['Manila Observatory','Philippines'],
        'QDM' : ['Queensland Department of Mines','Australia'],
        'QUE' : ['Pakistan Meteorological Department','Pakistan'],
        'QUI' : ['Escuela Politécnica Nacional','Ecuador'],
        'RAB' : ['Rabaul Volcanological Observatory','Papua New Guinea'],
        'RBA' : ['Université Mohammed V','Morocco'],
        'RDP' : ['Unknown Historical Agency',''],
        'REN' : ['MacKay School of Mines','U.S.A.'],
        'REY' : ['Icelandic Meteorological Office','Iceland'],
        'RIPT' : ['Research Inst. of Pulse Technique','Russia'],
        'RISSC' : ['Laboratory of Research on Experimental and Computational Seimology','Italy'],
        'RIV' : ['Riverview Observatory','Australia'],
        'RJOB' : ['Geophysikalisches Observatorium - Jochberg','Germany'],
        'RMIT' : ['Royal Melbourne Institute of Technology','Australia'],
        'RNON' : ['Geophysikalisches Observatorium - Staufen-Nonn','Germany'],
        'ROC' : ['Odenbach Seismic Observatory','U.S.A.'],
        'ROM' : ['Istituto Nazionale di Geofisica e Vulcanologia','Italy'],
        'ROTZ' : ['Geophysikalisches Observatorium - Rotzenmuhle','Germany'],
        'RRLJ' : ['Regional Research Laboratory Jorhat','India'],
        'RSMAC' : ['Red Sísmica Mexicana de Apertura Continental','Mexico'],
        'RSNC' : ['Red Sismológica Nacional de Colombia','Colombia'],
        'RSPR' : ['Red Sísmica de Puerto Rico','U.S.A.'],
        'RYD' : ['King Saud University','Saudi Arabia'],
        'SAN' : ['Santiago','Chile'],
        'SAPSE' : ['Southern Alps Passive Seismic Experiment','New Zealand'],
        'SAR' : ['Sarajevo Seismological Station','Bosnia and Herzegovina'],
        'SCB' : ['Observatorio San Calixto','Bolivia'],
        'SCE' : ['Geophysikalisches Observatorium - Schlegeis/Austria','Germany'],
        'SCEDC' : ['Southern California Earthquake Data Center','U.S.A.'],
        'SDD' : ['Universidad Autonoma de Santo Domingo','Dominican Republic'],
        'SEA' : ['Geophysics Program AK-50','U.S.A.'],
        'SEDA' : ['Seismic Exploration of the Deep Altiplano','U.S.A.'],
        'SEPA' : ['Seismic Experiment in Patagonia and Antarctica','U.S.A.'],
        'SET' : ['Setif Observatory','Algeria'],
        'SFS' : ['Real Instituto y Observatorio de la Armada','Spain'],
        'SGS' : ['Saudi Geological Survey','Saudi Arabia'],
        'SHI' : ['Shiraz Observatory','Iran'],
        'SHL' : ['Central Seismological Observatory','India'],
        'SIGU' : ['Subbotin Institute of Geophysics, National Academy of Sciences','Ukraine'],
        'SIK' : ['Seismic Institute of Kosovo',''],
        'SIO' : ['Scripps Institution of Oceanography','U.S.A.'],
        'SJA' : ['Instituto Nacional de Prevención Sísmica','Argentina'],
        'SJP' : ['Unknown Historical Agency',''],
        'SJS' : ['Instituto Costarricense de Electricidad','Costa Rica'],
        'SKHL' : ['Sakhalin Experimental and Methodological Seismological Expedition','Russia'],
        'SKL' : ['Sakhalin Complex Scientific Research Institute','Russia'],
        'SKO' : ['Seismological Observatory Skopje','FYR Macedonia'],
        'SLC' : ['Salt Lake City','U.S.A.'],
        'SLM' : ['Saint Louis University','U.S.A.'],
        'SMI' : ['Smithsonian Institution','U.S.A.'],
        'SNET' : ['Servicio Nacional de Estudios Territoriales','El Salvador'],
        'SNM' : ['New Mexico Institute of Mining and Technology','U.S.A.'],
        'SNSN' : ['Saudi National Seismic Network','Saudi Arabia'],
        'SOC' : ['Unknown Historical Agency',''],
        'SOD' : ['Sodankyla Seismological Station','Finland'],
        'SOF' : ['Geophysical Institute,  Bulgarian Academy of Sciences','Bulgaria'],
        'SOME' : ['Seismological Experimental Methodological Expedition','Kazakhstan'],
        'SPA' : ['USGS - South Pole','Antarctica'],
        'SPASE' : ['Southwest Pacific Seismic Experiment','U.S.A.'],
        'SPC' : ['Skalnate-Pleso Seismological Station','Slovakia'],
        'SPGM' : ['Service de Physique du Globe','Morocco'],
        'SPITAK' : ['','Armenia'],
        'SRI' : ['Stanford Research Institute','U.S.A.'],
        'SSN' : ['Sudan Seismic Network','Sudan'],
        'SSNC' : ['Servicio Sismológico Nacional Cubano','Cuba'],
        'SSS' : ['Centro de Estudios y Investigaciones Geotecnicas del San Salvador','El Salvador'],
        'STK' : ['Stockholm Seismological Station','Sweden'],
        'STL' : ['Santa Lucia Seismological Station','Chile'],
        'STR' : ['Institut de Physique du Globe','France'],
        'STU' : ['Stuttgart Seismological Station','Germany'],
        'SUC' : ['Unknown Historical Agency',''],
        'SUS' : ['Unknown Historical Agency',''],
        'SVA' : ['Department of Mineral Resources','Fiji'],
        'SVE' : ['Unknown Historical Agency',''],
        'SVSA' : ['Sistema de Vigilância Sismológica dos Açores','Portugal'],
        'SWE' : ['',''],
        'SYKES' : ['Sykes Catalogue of earthquakes 1950 onwards',''],
        'SYO' : ['National Institute of Polar Research','Japan'],
        'SZGRF' : ['Seismologisches Zentralobservatorium Gräfenberg','Germany'],
        'TAB' : ['Tabriz Seismological Observatory','Iran'],
        'TAC' : ['Estación Central de Tacubaya','Mexico'],
        'TAN' : ['Antananarivo','Madagascar'],
        'TANZANIA' : ['Tanzania Broadband Seismic Experiment','U.S.A.'],
        'TAP' : ['CWB',''],
        'TAS' : ['Unknown Historical Agency',''],
        'TAU' : ['University of Tasmania','Australia'],
        'TEH' : ['Tehran University','Iran'],
        'TEIC' : ['Center for Earthquake Research and Information','U.S.A.'],
        'THE' : ['Department of Geophysics,  Aristotle University of Thessaloniki','Greece'],
        'THR' : ['International Institute of Earthquake Engineering and Seismology (IIEES)','Iran'],
        'TIENSHAN' : ['Tien Shan Continental Dynamics','U.S.A.'],
        'TIF' : ['Seismic Monitoring Centre of Georgia','Georgia'],
        'TIR' : ['The Institute of Seismology,  Academy of Sciences of Albania','Albania'],
        'TOK' : ['Tokyo Observatory','Japan'],
        'TOL' : ['Toledo Observatory','Spain'],
        'TRI' : ['Istituto Nazionale di Oceanografia e di Geofisica Sperimentale (OGS)','Italy'],
        'TRN' : ['The University of the West Indies','Trinidad and Tobago'],
        'TTG' : ['Titograd Seismological Station','Montenegro'],
        'TUC' : ['Unknown Historical Agency',''],
        'TUL' : ['Oklahoma Geological Survey','U.S.A.'],
        'TUN' : ['Institut National de la Météorologie','Tunisia'],
        'TVA' : ['Tennessee Valley Authority','U.S.A.'],
        'TZN' : ['University of Dar Es Salaam','Tanzania'],
        'UAV' : ['Red Sismológica de Los Andes Venezolanos','Venezuela'],
        'UCC' : ['Royal Observatory of Belgium','Belgium'],
        'UCR' : ['Sección de Sismología,  Vulcanología y Exploración Geofísica','Costa Rica'],
        'UGN' : ['Institute of Geonics AS CR','Czech Republic'],
        'ULE' : ['University of Leeds','United Kingdom'],
        'UNAH' : ['Universidad Nacional Autonoma de Honduras','Honduras'],
        'UNK' : ['Unknown source',''],
        'UNKOWN' : ['Unknown source',''],
        'UPA' : ['Universidad de Panama','Panama'],
        'UPP' : ['University of Uppsala','Sweden'],
        'UPSL' : ['University of Patras, Department of Geology','Greece'],
        'USAEC' : ['United States Atomic Energy Commission','U.S.A.'],
        'USAF' : ['US Air Force Technical Applications Center','U.S.A.'],
        'USBR' : ['US Bureau of Reclamation','U.S.A.'],
        'USCGS' : ['United States Coast and Geodetic Survey','U.S.A.'],
        'USGS' : ['United States Geological Survey','U.S.A.'],
        'UUSS' : ['The University of Utah Seismograph Stations','U.S.A.'],
        'UVC' : ['Universidad del Valle','Colombia'],
        'VAO' : ['Instituto Astronomico e Geofísico','Brazil'],
        'VIE' : ['Österreichischer Geophysikalischer Dienst','Austria'],
        'VKMS' : ['Lab. of Seismic Monitoring, Voronezh region, GSRAS & Voronezh State University','Russia'],
        'VLA' : ['Vladivostok Seismological Station','Russia'],
        'VRAC' : ['Vranov Seismological Station','Czech Republic'],
        'VSI' : ['University of Athens','Greece'],
        'WAR' : ['Institute of Geophysics, Polish Academy of Sciences','Poland'],
        'WBNET' : ['West Bohemia Seismic Network','Czech Republic'],
        'WEL' : ['Institute of Geological and Nuclear Sciences','New Zealand'],
        'WES' : ['Weston Observatory','U.S.A.'],
        'WET' : ['Geophysikalisches Observatorium - Wettzell','Germany'],
        'WMO' : ['Wichita Mountains Observatory','U.S.A.'],
        'WOODLARK' : ['Woodlark-D, Entrecasteaux Rift, Papua New Guinea','U.S.A.'],
        'X' : ['Unknown Historical Agency',''],
        'YAL' : ['Unknown Historical Agency',''],
        'YARS' : ['Yakutiya Regional Seismological Center','Russia'],
        'ZAG' : ['Seismological Survey of the Republic of Croatia','Croatia'],
        'ZKW' : ['Unknown Historical Agency',''],
        'ZON' : ['Universidad Nacional de San Juan','Argentina'],
        'ZSC' : ['Zose Seismological Station','China'],
        'ZUR' : ['Swiss Seismological Service (SED)','Switzerland'],
        'ZUR_RMT' : ['Zurich Moment Tensors','Switzerland']}