sudo: false

language: python

python:
 - "3.6"

install:
  - pip install -U pip
  - pip install -r requirements-py36-linux64.txt
  - pip install -e .

script:
  - cd Demos; for f in *.py; do python $f; done 
